language: node_js
node_js:
- node
before_install:
- "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  skip_cleanup: true
  email: oscblgm@gmail.com
  api_key:
    secure: M9ftUhXTusyTREgMbxpDfUvPfl0On3GGqxZrftsX5ZEMLnmcNrsgLO9B6XoVbaVUjvfnS/IfaOYrMskmHpH0YUtLN1yhEWeoGhER/5WZNNgIHi0ms35n3ztYuUt8pyvXTuCDhlN7hEl+Ksj3pCohxTam4Xg969PuNphSUFLJKgjUWXuu8/0fJJAQ6SiMdBh3F+pxOy1huzHqlZ003tYxI1T5jDcweq1pJMuVW6zAN53GVy2TcMOZ63BbsvsC8WLu9qFCFVhAL/KWvASOf70BeK5bR2wczUa5lUa1zg9VXabdJ5wLaXAmW5Jk5y42knwPRJHuiOS/Dt130XWDSUdXAZgoD1UJRivUksuk9YXMTk+M/+BipIKRtumnPzXRpRTAx8exTHW+i8oavZW8EJHTz1COutAs4MkiujcisAucHnKeRO4cdKdDN/pK6FAsVLIIwA3Bj1dDKED/LZikjTwGFx5yIktujKb64AlQkWDsV08P7OmuMhQXPbjdvfd1T+gQZyhKq6gcfDB/IM/cHnEs5cJ7ykB5VOhT3E9fmza+zemvcRTetSGurqhaqbXuhcvb+MTR8coSga69GLIQjtaCJMuUNOJDUd52ulPjLGF6eSOCw0KkDNK3Gu+imhmva7hvu3McNvopVBbe4KTJk9qyyoBnOO6q78yqPEa/Vgdqaa4=
  on:
    repo: blgm/karma-buble-preprocessor
